# 1. Create a 3x3x3 array with random values

In [3]:
import numpy as np

# Create a 3x3x3 array with random values between 1 and 3
random_array = np.random.uniform(1, 3, size=(3, 3, 3))

# Print the random array
print(random_array)


[[[2.98418787 1.59607821 2.51362236]
  [1.46067622 1.59807042 2.29430649]
  [1.69451588 1.87716601 1.55238579]]

 [[2.97395645 1.93136493 2.81597309]
  [1.00020483 1.02643014 1.24183347]
  [2.2861225  1.2188763  2.85815329]]

 [[1.12762865 1.58046383 2.13207184]
  [2.84183534 2.8381838  1.10642081]
  [2.16462508 2.15808586 1.19292738]]]


# 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Fill values 1, 2, 3, 4 just below the diagonal
for i in range(1, 5):
    matrix[i, i - 1] = i

# Print the resulting matrix
print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3. Create a 8x8 matrix and fill it with a checkboard pattern

In [5]:
import numpy as np

# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8), dtype=int)

# Use array slicing to set alternate rows and columns to 1
matrix[1::2, ::2] = 1  # Odd rows, even columns
matrix[::2, 1::2] = 1  # Even rows, odd columns

# Print the resulting checkerboard pattern matrix
print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4.Normalize a 5*5 random matrix

In [47]:
import numpy as np

# Create a random 5x5 matrix
random_matrix = np.random.rand(5, 5)

# Calculate the mean and standard deviation of the matrix
mean = np.mean(random_matrix)
std_dev = np.std(random_matrix)

# Normalize the matrix
normalized_matrix = (random_matrix - mean) / std_dev

# Print the normalized matrix
print("Original matrix:")
print(random_matrix)
print("\nNormalized matrix:")
print(normalized_matrix)


Original matrix:
[[0.6405814  0.16626694 0.65970997 0.32977911 0.65201162]
 [0.55777572 0.98941528 0.83299479 0.22116616 0.49885917]
 [0.15706849 0.98006238 0.64145122 0.09878271 0.68109475]
 [0.65792877 0.92859685 0.26548267 0.33773643 0.8824493 ]
 [0.01787883 0.84114904 0.21257387 0.25177338 0.66847279]]

Normalized matrix:
[[ 0.38859481 -1.23192444  0.45394851 -0.67327687  0.42764671]
 [ 0.10568503  1.58040332  1.04598483 -1.04435849 -0.09560635]
 [-1.26335139  1.54844864  0.39156658 -1.46248769  0.52701069]
 [ 0.44786295  1.37261406 -0.8929489  -0.6460903   1.21494864]
 [-1.73889988  1.07384423 -1.07371446 -0.93978738  0.48388714]]


# 5. How to find common values between two arrays?

In [6]:
import numpy as np

# Define two NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([2, 4, 9, 6, 7])

# Find common values using np.intersect1d
common_values = np.intersect1d(array1, array2)

# Print the common values
print(common_values)


[2 4]


# 6. How to get the dates of yesterday today and tomorrow using numpy?

In [49]:
import numpy as np
from datetime import datetime, timedelta

# Define the current date
current_date = datetime.now()

# Calculate yesterday, today, and tomorrow
yesterday = current_date - timedelta(days=1)
today = current_date
tomorrow = current_date + timedelta(days=1)

# Create NumPy datetime64 arrays for yesterday, today, and tomorrow
dates = np.array([yesterday, today, tomorrow], dtype='datetime64[D]')

# Print the dates
print("Yesterday:", dates[0])
print("Today:", dates[1])
print("Tomorrow:", dates[2])


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7. Consider two random array A and B, Check if they are equal

In [18]:
import numpy as np

# Generate two random arrays A and B
size = 5  # You can change the size as needed
A = np.random.rand(size)
B = np.random.rand(size)

# Check if arrays A and B are equal
are_equal = np.array_equal(A, B)

# Print the result
if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


Arrays A and B are not equal.


# 8. Create random vector of size 10 and replace the maximum value by 0

In [20]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random Vector with the Maximum Value Replaced:")
print(random_vector)

Random Vector with the Maximum Value Replaced:
[0.93174829 0.35396127 0.17149381 0.68335884 0.         0.02383834
 0.13937023 0.03545659 0.22025706 0.23944292]


# 9. How to print all the values of an array?

In [23]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])

# Using a for loop to print values
for value in my_array:
    print(value)


1
2
3
4
5


# 10. Subtract the mean of each row of a matrix

In [27]:
import numpy as np

# Create a sample matrix (you can replace this with your matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the mean of each row along the columns (axis=1)
row_means = np.mean(matrix, axis=1)

# Subtract the row means from the matrix
centered_matrix = matrix - row_means[:, np.newaxis]

# Print the centered matrix
print(centered_matrix)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11. Consider a given vector, how to add 1 to each element indexed by a second vector( be careful with repeated indices)?

In [28]:
import numpy as np

# Given vector
given_vector = np.array([1, 2, 3, 4, 5])

# Second vector containing indices
second_vector_indices = np.array([1, 3, 0, 2, 3])

# Create an array to keep track of modified indices
modified_indices = np.zeros_like(given_vector, dtype=bool)

# Add 1 to elements indexed by the second vector
for index in second_vector_indices:
    if not modified_indices[index]:
        given_vector[index] += 1
        modified_indices[index] = True

# Print the resulting vector
print(given_vector)


[2 3 4 5 5]


# 12. How to get the diagonal of a dot product?

In [30]:
import numpy as np

# Define two matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Compute the dot product of A and B
dot_product = np.dot(A, B)

# Extract the diagonal elements of the dot product matrix
diagonal_elements = np.diag(dot_product)

print("Dot Product Matrix:")
print(dot_product)

print("\nDiagonal Elements of Dot Product:")
print(diagonal_elements)

Dot Product Matrix:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Diagonal Elements of Dot Product:
[30 69 90]


# 13. How to find the most frequent value in an array?

In [37]:
x = np.random.randint(0,20,50)
x

array([19, 18,  7,  6,  5, 10,  0, 16,  2,  5, 11,  2,  3,  6, 19, 18,  0,
        2,  4, 13, 11,  9, 18,  8,  0, 19, 19, 12, 11, 12,  0, 12,  0, 15,
        0, 19,  2, 19, 11, 16,  7, 14, 18, 14, 11, 11,  4,  0, 15, 14])

In [66]:
import numpy as np

# Create the random NumPy array
x = np.random.randint(0, 10, 50)

# Use NumPy to find the most frequent value
most_common_value = np.bincount(x).argmax()

print("Most frequent value:", most_common_value)

Most frequent value: 3


# 14. How to get the largest values of an array

In [60]:
import numpy as np

# Create a sample NumPy array (replace this with your array)
arr = np.array([10, 5, 8, 12, 15, 7, 20, 18])

# Find the largest values (let's find the top 3 largest values)
n = 3
largest_values = np.sort(arr)[-n:]

# Print the largest values
print(largest_values)


[15 18 20]


# 15. How to create a record array from a regular array?

In [68]:
import numpy as np

# Create a regular array with data
data = [(1, 'Pravs', 25),
        (2, 'Vaishu', 30),
        (3, 'Priya', 22)]

# Define data types and field names for the record array
dtypes = [('id', int), ('name', 'U10'), ('age', int)]

# Create the record array
record_array = np.array(data, dtype=dtypes)

# Access elements by field name
print(record_array['id'])   # Access the 'id' field
print(record_array['name']) # Access the 'name' field
print(record_array['age'])  # Access the 'age' field

[1 2 3]
['Pravs' 'Vaishu' 'Priya']
[25 30 22]


# 16.  How to swap two rows of an array?

In [48]:
import numpy as np

# Create an example 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Define the indices of the rows you want to swap
row1_index = 0  # Index of the first row (0-based)
row2_index = 2  # Index of the second row (0-based)

# Swap the rows
array[row1_index], array[row2_index] = array[row2_index].copy(), array[row1_index].copy()

print("Array with Rows Swapped:")
print(array)

Array with Rows Swapped:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


# 17. Write python code to reshape to the next dimension of numpy array?

In [50]:
import numpy as np

# Create the original array
x = np.array([[23, 34, 121],
              [23, 22, 67],
              [686, 434, 123]])

# Reshape the array to the next dimension
reshaped_array = x.reshape(-1, x.shape[-1])

print("Original Array:")
print(x)

print("\nReshaped Array to the Next Dimension:")
print(reshaped_array)

Original Array:
[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]

Reshaped Array to the Next Dimension:
[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]
